In [1]:
%%writefile shivam.txt
this is my new file
lol

Writing shivam.txt


In [5]:
x=open('shivam.txt')
x.read()

'this is my new file\nlol\n'

In [6]:
pwd

'C:\\Users\\91727\\pythonpracbootcamp'

In [8]:
x.close()

In [9]:
with open('shivam.txt') as n:
    new=n.read()

In [10]:
new

'this is my new file\nlol\n'

In [ ]:
-1pen('shivam.txt')

In [ ]:
x1=int(input())
x2=int(input())
x3=int(input())
r=int(input())
l1=[]
l2=[]
for i in range(x1,x2+1):
     l1.append(i)
print(l1)
for i in range(x3-r,x3+r):
     l2.append(i)
print(l2)

-1
-2


In [17]:
import numpy as np
  
# Taking a 3 * 3 matrix
A = np.array([[6, 24, 1],
              [13, 16, 10],
              [20, 17, 15]])
A2= np.array([[8, 5, 10],
              [21, 8, 21],
              [21, 12, 8]])
  
# Calculating the inverse of the matrix
B=(np.linalg.inv(A2))
print(B)
for i in range(3):
    for j in range(3):
        B[i][j]=(B[i][j])
print(B)
    

[[-0.2681883   0.11412268  0.03566334]
 [ 0.38944365 -0.20827389  0.05991441]
 [ 0.11982882  0.0128388  -0.05848787]]
[[-0.2681883   0.11412268  0.03566334]
 [ 0.38944365 -0.20827389  0.05991441]
 [ 0.11982882  0.0128388  -0.05848787]]
